module.exports = {
  classes: ["Barbarian",
            "Bard",
            "Cleric",
            "Druid",
            "Fighter",
            "Monk",
            "Paladin",
            "Ranger",
            "Rogue",
            "Sorcerer",
            "Warlock",
            "Wizard"],
  alignments: ["Lawful Good",
               "Neutral Good",
               "Chaotic Good",
               "Lawful Neutral",
               "Neutral",
               "Chaotic Neutral",
               "Lawful Evil",
               "Neutral Evil",
               "Chaotic Evil"],
  traits: ["Seeks to lift their curse.",
           "Always the target of enemy attacks.",
           "Pacifist.",
           "Would rather sleep beneath the stars than a roof.",
           "Loves to take risks.",
           "Stops to water thirsty flora.",
           "Lived as a hermit.",
           "Quite clearly two gnomes in a trenchcoat.",
           "Can only sleep during the day.",
           "Plans to betray their party.",
           "Amateur alchemist.",
           "Dreams of becoming a chef.",
           "Carries around their favourite book.",
           "Works at a secret base on the moon.",
           "Nomadic lifestyle.",
           "Fiercely protective of their allies.",
           "Not welcome in at least three townships.",
           "Cannot return home.",
           "Thirsts for revenge.",
           "Made a deal with the devil.",
           "Knits sweaters for their party.",
           "Trapped in another dimension.",
           "Fights to clear their family's name.",
           "Life was changed by a stranger.",
           "Moonlights as a court jester.",
           "Used to be mayor.",
           "Has a wolf companion.",
           "Trying to decipher an ancient tome.",
           "The world's greatest dancer.",
           "Speaks five languages.",
           "Never leaves home without their lucky dice.",
           "Skilled at Dragonchess.",
           "Constantly running out of inventory space.",
           "Banned from the local tavern.",
           "Traded away their memories.",
           "Doesn't know that the villain is their childhood friend.",
           "The chosen one.",
           "Named their weapon.",
           "Learning magic.",
           "Incurred the ire of a powerful enemy.",
           "The leader of the party.",
           "Member of a spy network.",
           "Wields a comically oversized weapon.",
           "Their name instills fear into their enemies.",
           "Knows something that no one should know.",
           "Always brings extra blankets, just in case.",
           "Carries the hopes of their village.",
           "Running from their past.",
           "Loots. Everything.",
           "Terrible at lying.",
           "Loves shopping upon entering a new town.",

           "Really picky eater.",
           "Loves to snack.",
           "Always daydreams.",
           "Is friends with everyone.",
           "Sings songs by the campfire.",
           "Always late.",
           "Prefers the rain.",
           "Highly competitive."]
}
